// File generated by Pepinillo, If you edit this file, rename it and/or delete the .feature file that generates it.

namespace pepin;
#nullable enable
using Microsoft.VisualStudio.TestTools.UnitTesting;

// /Users/jim/dev/datagrove/testing/dotnet/template/pepin_simple/feature/Calc.feature
[TestClass()]
[TestCategory("pepin")]
public class Calculator 
{
    public TestContext? TestContext { get; set; }
    
    public class Steps {

        public Steps(StepState actor)
        {

            var step=this;

        }
    }

    [TestMethod()]
    public async Task Add_two_numbers()
    {
    await using (var actor = new {StepState}(TestContext!)){
        var step = new Steps(actor);
        }
    }
    [TestMethod()]
    public async Task Add_two_numbers__1()
    {
    await using (var actor = new {StepState}(TestContext!)){
        var step = new Steps(actor);
        }
    }

    
}
